version: '3.9'

services:
  db:
    image: postgres
    container_name: mypostgres
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  grafana_app:
    image: grafana/grafana
    container_name: mygrafana
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./grafana_data:/data
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '2.0'
